spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
